### ISSUE TITLE
New release v0.18.2

### ISSUE THREAD

**Issue by danie-dejager** [purveshpatel511/batwing#3]
Hi,

Can you please release the latest version?

Danie

**Comment by purveshpatel511** [comment]
hi @daniejstriata. I released bat v0.18.2 on snapcraft store. I still mention that batcat doesn't get classic confinement from review-team of snapcraft so this release of snap is not able to access hidden and root directory files.

If there is any other problem, please open an issue here.

Thank You for your support.

**Comment by danie-dejager** [comment]
@purveshpatel511 Thank you. I'm having the same problem for another utility I published. The reviewers don't want to approve my classic confinement request although I'd think that if the software is not capable to use strict confinement it should be allowed to use classic confinement.

**Comment by purveshpatel511** [comment]
Hey @daniejstriata, If you are also working on building snap then please comment your snapcraft forum id in this thread. I have stuck on issue and really would some help there.

**Comment by danie-dejager** [comment]
Hi,

Sure. I'm still learning myself. Still trying to figure out what, where, when and WFT!

faramirza

________________________________

**Comment by purveshpatel511** [comment]
Yeah, I checked your profile and found that you were build few snap using build-override method and i really need some help over there.
